//Hämtr hela arrayen med alla produkter (böcker) 
GET http://localhost:3000/products
###
 
//Hämtar en spesifik produkt - om inte produkten finns svarar APIét med 404
GET http://localhost:3000/products/1234567
###
 
//Lägger till en ny produkt 
POST  http://localhost:3000/products
Content-Type: application/json
 
{
 "id":"1823998",
 "Titel": "Ny bok1",
 "Författare": "Jhon Doe",
 "Pris": 299
}
###
 
//Uppdaterar en produkt - titel och pris ändrat
PUT http://localhost:3000/products/1234567 
Content-Type: application/json

{
"id": "1234567",
    "Titel": "Där kräftorna sjunger lalallala",
    "Författare": "Delia Owens",
    "Pris": 389,
    "image": "OnePlus5.png"
}
###

//Ta bort en produkt
DELETE http://localhost:3000/products/1234567
###
 
